-- Migration: V4 - Criação da tabela de produtos
-- Padrão da disciplina: chaves primárias com prefixo 'id_'
CREATE TABLE produtos (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL UNIQUE,
    categoria VARCHAR(20) NOT NULL,
    estoque_atual INT NOT NULL,
    estoque_minimo INT NOT NULL,
    unidade_medida VARCHAR(20) NOT NULL,
    data_cadastro DATE NOT NULL
);

-- Índices para otimização de buscas
CREATE INDEX idx_produtos_nome ON produtos(nome);
CREATE INDEX idx_produtos_categoria ON produtos(categoria);
